# Generated by Django 3.2.9 on 2021-12-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Building Name')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=20)),
                ('building', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataviz.building')),
            ],
        ),
        migrations.CreateModel(
            name='HalfHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(blank=True, default=None, null=True)),
                ('reading_date_time', models.DateTimeField(blank=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataviz.meter')),
            ],
        ),
    ]
